name: 'Benchmark'

on:
  workflow_call:
    inputs:
      java-version:
        default: '19'
        required: false
        type: string
      jmh-results-path:
        default: 'jmh/results.txt'
        required: false
        type: string
    secrets:
      github-token:
        required: true

jobs:
  earlyaccess:
    name: 'Benchmark'
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous run
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ secrets.github-token }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'zulu'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('**/gradle.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Cache Gradle wrapper
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradlew-${{ hashFiles('**/gradlew') }}
          restore-keys: ${{ runner.os }}-gradlew-

      - name: Build
        run: |
          ./gradlew jmh -S

      - name: Upload benchmark report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-report
          path: |
            ${{ inputs.jmh-results-path }}