name: Build

on:
  workflow_call:
    inputs:
      java-version:
        default: '21'
        required: false
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: ./.github/actions/setup-gradle
        with:
          java-version: ${{ inputs.java-version }}

      - name: Build
        run: |
          ./gradlew build aggregateTestReports -S
        
      - name: Upload test reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            build/reports/aggregate-tests/