name: 'Early Access'

on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string
      platforms:
        default: 'linux/amd64,linux/arm64'
        required: false
        type: string
    secrets:
      github-token:
        required: true
      docker-username:
        required: true
      docker-password:
        required: true

jobs:
  docker:
    name: 'Docker'
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous run
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ secrets.github-token }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.docker-username }}
          password: ${{ secrets.docker-password }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ inputs.tags }}
          platforms: ${{ inputs.platforms }}
