name: 'Early Access'

on:
  workflow_call:
    inputs:
      jreleaser-version:
        default: 'latest'
        required: false
        type: string
      jreleaser-arguments:
        default: 'release'
        required: false
        type: string
      java-version:
        default: '21'
        required: false
        type: string
    secrets:
      github-user:
        required: false
      github-token:
        required: true
      gpg-passphrase:
        required: true
      gpg-public-key:
        required: true
      gpg-secret-key:
        required: true
      sonatype-username:
        required: false
      sonatype-password:
        required: false
      docker-username:
        required: false
      docker-password:
        required: false
      slack-webhook:
        required: false

jobs:
  earlyaccess:
    name: 'Early Access'
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous run
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ secrets.github-token }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'zulu'

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build
        run: |
          ./mvnw --no-transfer-progress -B --file pom.xml verify

      - name: Upload test reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/
  
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4

      - name: Version
        id: vars
        shell: bash
        run: |
          echo version=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_OUTPUT

      - name: Release
        uses: jreleaser/release-action@v2
        with:
          arguments: ${{ inputs.jreleaser-arguments }}
          version: ${{ inputs.jreleaser-version }}
        env:
          JRELEASER_PROJECT_VERSION: ${{ steps.vars.outputs.VERSION }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.github-token }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.gpg-passphrase }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.gpg-public-key }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.gpg-secret-key }}
          JRELEASER_DOCKER_DEFAULT_USERNAME: ${{ secrets.docker-username }}
          JRELEASER_DOCKER_DEFAULT_PASSWORD: ${{ secrets.docker-password }}
          JRELEASER_NEXUS2_USERNAME: ${{ secrets.sonatype-username }}
          JRELEASER_NEXUS2_PASSWORD: ${{ secrets.sonatype-password }}
          JRELEASER_GITHUB_USERNAME: ${{ secrets.github-user }}
          JRELEASER_GITHUB_PASSWORD: ${{ secrets.github-token }}
          JRELEASER_SLACK_WEBHOOK: ${{ secrets.slack-webhook }}

      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties
