name: Publish

on:
  workflow_call:
    inputs:
      branch:
        default: 'master'
        required: false
        type: string
      version:
        description: "Release version"
        required: true
        type: string
      java-version:
        default: '21'
        required: false
        type: string
    secrets:
      github-token:
        required: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{ inputs.java-version }}

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set release version
        run: |
          VERSION=${{ inputs.version }}
          ./mvnw versions:set -DnewVersion=$VERSION

      - name: Build
        run: |
          ./mvnw --no-transfer-progress -B --file pom.xml process-resources

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.github-token }}
          publish_dir: ./target/generated-docs
