name: Release

on:
  workflow_call:
    inputs:
      branch:
        default: 'master'
        required: false
        type: string
      version:
        required: true
        type: string
      jreleaser-version:
        default: 'latest'
        required: false
        type: string
      java-version:
        default: '21'
        required: false
        type: string
      tasks:
        default: 'build aggregateTestReports publish'
        required: false
        type: string
    secrets:
      github-user:
        required: false
      github-token:
        required: true
      gpg-passphrase:
        required: true
      gpg-public-key:
        required: true
      gpg-secret-key:
        required: true
      docker-username:
        required: false
      docker-password:
        required: false
      sonatype-username:
        required: false
      sonatype-password:
        required: false
      slack-webhook:
        required: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous run
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ secrets.github-token }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'zulu'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache Gradle wrapper
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradlew-${{ hashFiles('**/gradlew') }}
          restore-keys: ${{ runner.os }}-gradlew-

      - name: Set release version
        run: |
          VERSION=${{ inputs.version }}
          echo $VERSION > VERSION

      - name: Build
        run: |
          ./gradlew -Pprofile=release -PreproducibleBuild=true ${{ inputs.tasks }} -S
        env:
          GRGIT_USER: ${{ secrets.github-user }}
          GRGIT_PASS: ${{ secrets.github-token }}

      - name: Upload test reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            build/reports/aggregate-tests/

      - name: Assemble
        uses: jreleaser/release-action@v2
        with:
          arguments: assemble
          version: ${{ inputs.jreleaser-version }}
        env:
          JRELEASER_PROJECT_VERSION: ${{ inputs.version }}

      - name: Release
        uses: jreleaser/release-action@v2
        with:
          arguments: full-release
          version: ${{ inputs.jreleaser-version }}
        env:
          JRELEASER_PROJECT_VERSION: ${{ inputs.version }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.github-token }}
          JRELEASER_BRANCH: ${{ inputs.branch }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.gpg-passphrase }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.gpg-public-key }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.gpg-secret-key }}
          JRELEASER_DOCKER_DEFAULT_USERNAME: ${{ secrets.docker-username }}
          JRELEASER_DOCKER_DEFAULT_PASSWORD: ${{ secrets.docker-password }}
          JRELEASER_NEXUS2_USERNAME: ${{ secrets.sonatype-username }}
          JRELEASER_NEXUS2_PASSWORD: ${{ secrets.sonatype-password }}
          JRELEASER_SLACK_WEBHOOK: ${{ secrets.slack-webhook }}

      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties

      - name: Commit release version
        run: |
          VERSION=${{ inputs.version }}
          sed -i -e "s/^\:project-version\:\ .*/:project-version: $VERSION/g" README.adoc
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Action"
          git add VERSION README.adoc
          git commit -a -m "Releasing version $VERSION"
          git push origin ${{ inputs.branch }}