name: Release

on:
  workflow_call:
    inputs:
      branch:
        default: 'main'
        required: false
        type: string
      version:
        description: "Release version"      
        required: true
        type: string
      jreleaser-version:
        default: 'latest'
        required: false
        type: string
      java-version:
        default: '21'
        required: false
        type: string
      publish:
        default: false
        required: true
        type: boolean
    secrets:
      github-user:
        required: false
      github-token:
        required: true
      gpg-passphrase:
        required: true
      gpg-public-key:
        required: true
      gpg-secret-key:
        required: true
      docker-username:
        required: false
      docker-password:
        required: false
      sonatype-username:
        required: false
      sonatype-password:
        required: false
      slack-webhook:
        required: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous run
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ secrets.github-token }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'zulu'

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set release version
        run: |
          VERSION=${{ inputs.version }}
          ./mvnw versions:set -DnewVersion=$VERSION

      - name: Build
        run: |
          ./mvnw --no-transfer-progress -B --file pom.xml verify

      - name: Upload test reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            target/

      - name: Assemble
        uses: jreleaser/release-action@v2
        with:
          arguments: assemble
          version: ${{ inputs.jreleaser-version }}
        env:
          JRELEASER_PROJECT_VERSION: ${{ inputs.version }}

      - name: Release
        uses: jreleaser/release-action@v2
        with:
          arguments: full-release
          version: ${{ inputs.jreleaser-version }}
        env:
          JRELEASER_PROJECT_VERSION: ${{ inputs.version }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.github-token }}
          JRELEASER_BRANCH: ${{ inputs.branch }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.gpg-passphrase }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.gpg-public-key }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.gpg-secret-key }}
          JRELEASER_DOCKER_DEFAULT_USERNAME: ${{ secrets.docker-username }}
          JRELEASER_DOCKER_DEFAULT_PASSWORD: ${{ secrets.docker-password }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.sonatype-username }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.sonatype-password }}
          JRELEASER_GITHUB_USERNAME: ${{ secrets.github-user }}
          JRELEASER_GITHUB_PASSWORD: ${{ secrets.github-token }}
          JRELEASER_SLACK_WEBHOOK: ${{ secrets.slack-webhook }}

      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties
            
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ inputs.publish }} == true
        with:
          github_token: ${{ secrets.github-token }}
          publish_dir: ./target/generated-docs

      - name: Commit release version
        run: |
          VERSION=${{ inputs.version }}
          sed -i -e "s/^\:project-version\:\ .*/:project-version: $VERSION/g" README.adoc
          ./mvnw build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Action"
          git add pom.xml README.adoc
          git commit -a -m "Releasing version $VERSION"
          git push origin ${{ inputs.branch }}